exclude: '.venv'
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
        name: Checagem de Arquivos YAML

    -   id: end-of-file-fixer
        name: Checagem de Última Linha do Arquivo em Branco
        verbose: true

    -   id: trailing-whitespace
        name: Checagem de Espaço em Branco Sobrando
        verbose: true

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
        - id: ruff
          name: Linter do Ruff
          types_or: [ python, pyi ]
          args: [ --fix ]

        - id: ruff-format
          name: Formater do Ruff
          types_or: [ python, pyi ]
